spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

token:
  secret:
    key: ${TOKEN_SECRET_KEY}
  access-token:
    plus-hour : 1
  refresh-token:
    plus-hour : 12