spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3307/dev-together?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

token:
  secret:
    key: devTogether1234JwtHelperTokenSecretKeyValue6352
  access-token:
    plus-hour : 1
  refresh-token:
    plus-hour : 12